<a href="https://colab.research.google.com/github/geonho27/DEEP_Learning/blob/main/inclass/%EB%94%A5%EB%9F%AC%EB%8B%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

addOperation = tf.matmul(a, b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a: [[1,2,3], [1,2,3], [1,2,3]], b: [[1,5,2], [1,2,3], [1,2,3]]}))

[[ 6. 15. 17.]
 [ 6. 15. 17.]
 [ 6. 15. 17.]]


In [12]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.float32)
b = tf.constant([5,5,5], tf.float32)
addOperation = tf.add(a, b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a:[1,2,3]}))

[6. 7. 8.]


In [20]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.float32)
b = tf.constant([5,5,5], tf.float32)
addOperation = tf.add(a, b)
minusOperation = tf.subtract(a, b)
mulOperation = tf.multiply(a, b)
divOperation = tf.divide(a, b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a: [5,10,20], b: [2, 5, 5]}))
  print(sess.run(minusOperation, {a: [5,10,20], b: [2, 5, 5]}))
  print(sess.run(mulOperation, {a: [5,10,20], b: [2, 5, 5]}))
  print(sess.run(divOperation, {a: [5,10,20], b: [2, 5, 5]}))

[ 7. 15. 25.]
[ 3.  5. 15.]
[ 10.  50. 100.]
[2.5 2.  4. ]


In [24]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
addOperation = tf.matmul(a, b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a: [[1, 2, 3], [3, 4, 5], [1, 1, 1]], b: [[2, 1],[1,2], [1, 1]] }))


[[ 7.  8.]
 [15. 16.]
 [ 4.  4.]]


In [34]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


x = tf.Variable(10, name="x")

y = tf.Variable(20, name="y")

z1 = tf.add(x, y, name = "z1")

z2 = tf.multiply(x, y, name = "z2")

z3 = tf.multiply(z1, z2, name = "z3")

init = tf.global_variables_initializer()
with tf.compat.v1.Session() as sess:
  sess.run(init)
  y = tf.Variable(1)
  print(sess.run(z3))



6000
